apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: devops-cicd
data:
   user-login:  YWRtaW4= # admin
   user-name: YWRtaW4= # admin
   user-password: YWRtaW4= # admin   