version: '3.8'

services:
  cluster:
    build:
      context: ./cluster
    #image:  golang:1.17-alpine -> docker dind alpine
    container_name: kind-cluster
    restart: always     
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    tty: true        
    networks:
      - kind-net 
networks:
  kind-net:
    driver: bridge
    name: kind