apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-cicd  
spec:
  selector:
    matchLabels:
      app: mysql
      workload: cicd
  strategy:
    type: Recreate      
  replicas: 1
  template: 
    metadata:
      namespace: devops-cicd      
      labels:
        app: mysql 
        workload: cicd        
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.32
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-db-name 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                name: mysql-secret
                key: mysql-root-pass
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim              
      restartPolicy: Always        
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: devops-cicd    
spec:
  selector:
    app: mysql
    workload: cicd    
  ports:
    - name: http
      port: 3306
      nodePort: 30033
  type: NodePort