apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-cicd    
spec:
  selector:
    matchLabels:
      app: nexus
      workload: cicd
  replicas: 1
  template: 
    metadata:
      labels:
        app: nexus 
        workload: cicd
      namespace: devops-cicd          
    spec:
      containers: 
      - name: nexus
        image: sonatype/nexus3:3.37.0
        volumeMounts:
        - name: nexus-persistent-storage
          mountPath: /nexus-data
      # Give access on volume
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
        volumeMounts:
        - name: nexus-persistent-storage
          mountPath: /nexus-data               
      volumes:
      - name: nexus-persistent-storage
        persistentVolumeClaim:
          claimName: nexus-pv-claim              
      restartPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-cicd    
spec:
  selector:
    app: nexus
    workload: cicd
  ports:
    - name: http
      port: 8081
      nodePort: 30081
  type: NodePort