apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: devops-cicd
  name: nexus-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 700Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nexus/"
    type: DirectoryOrCreate    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops-cicd
  name: nexus-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi  # Must be equal or greater than Storage capacity specified in pv