FROM jenkins/jenkins:lts

ARG MAVEN_V

# Install docker pipeline plugin
#RUN jenkins-plugin-cli --plugins docker-workflow:1.27

# change to root
USER root

# install wget
RUN apt-get update && apt-get install -y wget openssh-server

# Download maven binaries
RUN wget --no-verbose -O /tmp/apache-maven-$MAVEN_V-bin.tar.gz http://apache.cs.utah.edu/maven/maven-3/$MAVEN_V/binaries/apache-maven-$MAVEN_V-bin.tar.gz

# install maven
RUN tar xzf /tmp/apache-maven-$MAVEN_V-bin.tar.gz -C /opt/ \
    && ln -s /opt/apache-maven-$MAVEN_V /opt/maven \
    && ln -s /opt/maven/bin/mvn /usr/local/bin \
    && rm -f /tmp/apache-maven-$MAVEN_V-bin.tar.gz

RUN chown -R jenkins:jenkins /opt/maven

# Setup maven home
ENV MAVEN_HOME /opt/maven

# remove download archive files and cache
RUN apt-get clean
RUN rm -rf /var/cache/apt/*

# Run ssh daemon
EXPOSE 22
RUN mkdir /run/sshd
CMD [ "sh","-c","/usr/sbin/sshd && /usr/local/bin/jenkins.sh"]


# volume for Jenkins settings
VOLUME /var/jenkins_home
