# Validate docker-compose stack
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: docker-compose up --build -d

      # Check for jenkins and docker dind containers
      - name: Check running containers (Jenkins + docker dind)
        run: docker ps -a  

      # Create cluster
      - name: Create kind cluster with 2 control-plane nodes and 3 worker nodes
        run: docker exec -t kind-cluster sh -c "echo -e '2\n3' | ./cluster-setup.sh"
      
      # Validate cluster nodes
      - name: Get cluster nodes
        run: docker exec -t kind-cluster kubectl get nodes
      
      # Pull nginx image and apply deployment
      - name: Pull nginx and apply deployment
        # Could use kind load docker-image nginx:1 --name k8s-cluster to download image to avoid timout error
        run: docker exec -t kind-cluster sh -c "apk --no-cache  add curl && kubectl apply -f ./nginx-deployment.yaml && kubectl wait --for=condition=ready pod -l app=nginx1.14.2 --timeout=30s && curl k8s-cluster-control-plane:30080"
      
      # Check k8s resources
      - name: Get k8s resources
        run: docker exec -t kind-cluster kubectl get all
   