apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
      workload: cicd
  replicas: 1
  template: 
    metadata:
      labels:
        app: jenkins 
        workload: cicd        
    spec:
      containers:
      # For depends on you can either use helm chart
      # or just specify the db container here
      - name: jenkins
        image: jenkins/jenkins:latest
        #imagePullPolicy: Never            
      restartPolicy: Always        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
    workload: cicd
  ports:
    - name: http
      port: 8080
      nodePort: 30082
  type: NodePort