apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
      workload: cicd
  replicas: 1
  template: 
    metadata:
      labels:
        app: nexus 
        workload: cicd
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.37.0
      restartPolicy: Always        
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
    workload: cicd
  ports:
    - name: http
      port: 8081
      nodePort: 30081
  type: NodePort